//
// Created by Shadow on 12/2/2020.
//

#ifndef PERFORMANCEEVALUATIONMULTITHREAD_READER_WRITERSTATAS_H
#define PERFORMANCEEVALUATIONMULTITHREAD_READER_WRITERSTATAS_H

#include <stdlib.h>
#include <pthread.h>
#include "mySemTAS.h"
#include "TATAS.h"
#endif //PERFORMANCEEVALUATIONMULTITHREAD_READER_WRITERSTATAS_H
